import type { Archetype } from "@/domain/types";

export const archetypes: readonly Archetype[] = [
  {
    id: "alchemist",
    name: "The Alchemist",
    description: "Transforms pain, pattern, and pressure into usable wisdom.",
    coreWound: "Believing the past must define the future.",
    coreGift: "Transmutation",
    startingStats: {
      clarity: 2,
      courage: 2,
      selfWorth: 1,
      boundaries: 1,
      emotionalRegulation: 2,
      compassion: 1,
      creativity: 2,
      discipline: 1,
      intuition: 2,
      presence: 1,
    },
  },
  {
    id: "architect",
    name: "The Architect",
    description: "Builds order, structure, and momentum from inner chaos.",
    coreWound: "Feeling unsafe without control.",
    coreGift: "Sacred structure",
    startingStats: {
      clarity: 2,
      courage: 1,
      selfWorth: 1,
      boundaries: 2,
      emotionalRegulation: 1,
      compassion: 1,
      creativity: 1,
      discipline: 3,
      intuition: 1,
      presence: 2,
    },
  },
  {
    id: "creator",
    name: "The Creator",
    description: "Restores vitality through expression, imagination, and play.",
    coreWound: "Hiding expression to stay accepted.",
    coreGift: "Creative renewal",
    startingStats: {
      clarity: 1,
      courage: 1,
      selfWorth: 2,
      boundaries: 1,
      emotionalRegulation: 1,
      compassion: 1,
      creativity: 3,
      discipline: 1,
      intuition: 2,
      presence: 2,
    },
  },
  {
    id: "healer",
    name: "The Healer",
    description: "Meets wounded places with compassion and restores wholeness.",
    coreWound: "Carrying others while abandoning the self.",
    coreGift: "Compassionate repair",
    startingStats: {
      clarity: 1,
      courage: 1,
      selfWorth: 1,
      boundaries: 1,
      emotionalRegulation: 2,
      compassion: 3,
      creativity: 1,
      discipline: 1,
      intuition: 2,
      presence: 2,
    },
  },
  {
    id: "seer",
    name: "The Seer",
    description: "Finds truth beneath illusion, projection, and inherited story.",
    coreWound: "Doubting inner knowing.",
    coreGift: "Vision",
    startingStats: {
      clarity: 3,
      courage: 1,
      selfWorth: 1,
      boundaries: 1,
      emotionalRegulation: 1,
      compassion: 1,
      creativity: 1,
      discipline: 1,
      intuition: 3,
      presence: 2,
    },
  },
  {
    id: "warrior",
    name: "The Warrior",
    description: "Protects the true self through action, courage, and devotion.",
    coreWound: "Confusing peace with self-abandonment.",
    coreGift: "Courageous protection",
    startingStats: {
      clarity: 1,
      courage: 3,
      selfWorth: 1,
      boundaries: 2,
      emotionalRegulation: 1,
      compassion: 1,
      creativity: 1,
      discipline: 2,
      intuition: 1,
      presence: 2,
    },
  },
];
