import type { Boss } from "@/domain/types";

export const bosses: readonly Boss[] = [
  {
    id: "abandoner",
    name: "The Abandoner",
    description: "The part that leaves the self first to avoid being left.",
    roomId: "childhood-room",
    reflectionPrompt: "Where do you leave yourself before anyone else can?",
    rewardIds: ["inner-child-gem"],
    unlockRequirements: [{ type: "completedRitual", ritualId: "first-memory" }],
  },
  {
    id: "ancestral-thread",
    name: "The Ancestral Thread",
    description: "An inherited loyalty that keeps repeating through the body.",
    roomId: "ancestral-chamber",
    reflectionPrompt: "What pattern are you carrying out of loyalty?",
    rewardIds: ["thread-cutter"],
    unlockRequirements: [{ type: "completedRitual", ritualId: "lineage-mapping" }],
  },
  {
    id: "avoider",
    name: "The Avoider",
    description: "The force that delays truth to preserve temporary comfort.",
    roomId: "shadow-mirror-hall",
    reflectionPrompt: "What truth has comfort trained you to postpone?",
    rewardIds: ["shadow-courage"],
    unlockRequirements: [{ type: "completedRitual", ritualId: "shadow-dialogue" }],
  },
  {
    id: "chaos-weaver",
    name: "The Chaos Weaver",
    description: "A restless force that scatters attention before momentum forms.",
    roomId: "future-self-chamber",
    reflectionPrompt: "Where does chaos protect you from committed action?",
    rewardIds: ["future-vow"],
    unlockRequirements: [{ type: "ascensionPointsMinimum", minimum: 50 }],
  },
  {
    id: "clinger",
    name: "The Clinger",
    description: "The attachment fear that confuses closeness with control.",
    roomId: "relationship-atrium",
    reflectionPrompt: "What do you try to hold when you feel unsafe?",
    rewardIds: ["attachment-clarity"],
    unlockRequirements: [{ type: "completedRitual", ritualId: "attachment-mapping" }],
  },
  {
    id: "critic",
    name: "The Critic",
    description: "The inner voice that attacks before the world can judge.",
    roomId: "hall-of-echoes",
    reflectionPrompt: "What is the critic trying to prevent you from risking?",
    rewardIds: ["pattern-sight"],
    unlockRequirements: [{ type: "completedRitual", ritualId: "pattern-naming" }],
  },
  {
    id: "ghost",
    name: "The Ghost",
    description: "The fading self that stays unseen to stay safe.",
    roomId: "archetype-chamber",
    reflectionPrompt: "Where have you become invisible to avoid consequence?",
    rewardIds: ["archetype-sigil"],
    unlockRequirements: [{ type: "completedRitual", ritualId: "archetype-activation" }],
  },
  {
    id: "martyr",
    name: "The Martyr",
    description: "The part that earns love by overgiving and self-erasure.",
    roomId: "chamber-of-boundaries",
    reflectionPrompt: "Where do you call self-abandonment generosity?",
    rewardIds: ["boundary-flame"],
    unlockRequirements: [{ type: "completedRitual", ritualId: "line-in-the-sand" }],
  },
  {
    id: "performer",
    name: "The Performer",
    description: "The mask that trades truth for approval.",
    roomId: "hall-of-masks",
    reflectionPrompt: "What approval do you fear losing if you become honest?",
    rewardIds: ["mask-shard"],
    unlockRequirements: [{ type: "completedRitual", ritualId: "mask-removal" }],
  },
  {
    id: "saboteur",
    name: "The Saboteur",
    description: "The protector that ruins momentum before change becomes real.",
    roomId: "shadow-mirror-hall",
    reflectionPrompt: "What success would force you to stop believing?",
    rewardIds: ["transmutation-ash"],
    unlockRequirements: [
      { type: "completedRitual", ritualId: "fire-of-transmutation" },
    ],
  },
  {
    id: "scarcity-beast",
    name: "The Scarcity Beast",
    description: "The fear that there is not enough safety, love, time, or worth.",
    roomId: "scarcity-vault",
    reflectionPrompt: "What do you believe you must hoard to survive?",
    rewardIds: ["scarcity-release"],
    unlockRequirements: [{ type: "completedRitual", ritualId: "worthiness-recode" }],
  },
  {
    id: "shadow-child",
    name: "The Shadow Child",
    description: "The younger wound that acts out until it is heard.",
    roomId: "childhood-room",
    reflectionPrompt: "What does the younger self need you to stop ignoring?",
    rewardIds: ["inner-child-gem"],
    unlockRequirements: [
      { type: "completedRitual", ritualId: "inner-child-embrace" },
    ],
  },
];
