import type { Quest } from "@/domain/types";

export const quests: readonly Quest[] = [
  {
    id: "arrive-at-threshold",
    title: "Arrive at the Threshold",
    description: "Complete the first arrival ritual and record one honest truth.",
    type: "trial",
    roomId: "threshold-chamber",
    ritualId: "breath-of-arrival",
    rewardIds: ["arrival-spark"],
  },
  {
    id: "name-the-pattern",
    title: "Name the Pattern",
    description: "Identify one repeating pattern without judging it.",
    type: "trial",
    roomId: "hall-of-echoes",
    ritualId: "pattern-naming",
    rewardIds: ["pattern-sight"],
    unlockRequirements: [{ type: "trialDayMinimum", day: 2 }],
  },
  {
    id: "meet-the-origin",
    title: "Meet the Origin",
    description: "Return to an early memory and offer compassion.",
    type: "trial",
    roomId: "childhood-room",
    ritualId: "first-memory",
    rewardIds: ["origin-compassion"],
    unlockRequirements: [{ type: "trialDayMinimum", day: 3 }],
  },
  {
    id: "face-the-shadow",
    title: "Face the Shadow",
    description: "Complete a dialogue with an avoided part of the self.",
    type: "trial",
    roomId: "shadow-mirror-hall",
    ritualId: "shadow-dialogue",
    rewardIds: ["shadow-courage"],
    unlockRequirements: [{ type: "trialDayMinimum", day: 4 }],
  },
  {
    id: "activate-the-archetype",
    title: "Activate the Archetype",
    description: "Name one action that expresses the chosen archetype today.",
    type: "trial",
    roomId: "archetype-chamber",
    ritualId: "archetype-activation",
    rewardIds: ["archetype-sigil"],
    unlockRequirements: [{ type: "trialDayMinimum", day: 5 }],
  },
  {
    id: "defeat-first-boss",
    title: "Defeat the First Boss",
    description: "Confront the first active boss and claim its lesson.",
    type: "trial",
    bossId: "ghost",
    rewardIds: ["thread-cutter"],
    unlockRequirements: [
      { type: "completedRitual", ritualId: "archetype-activation" },
    ],
  },
  {
    id: "unlock-the-library",
    title: "Unlock the Library",
    description: "Complete the initiation and open the wider library path.",
    type: "trial",
    rewardIds: ["library-key"],
    unlockRequirements: [{ type: "trialDayMinimum", day: 7 }],
  },
  {
    id: "hold-a-clean-boundary",
    title: "Hold a Clean Boundary",
    description: "Choose one honest no or clear request and act on it.",
    type: "room",
    roomId: "chamber-of-boundaries",
    ritualId: "line-in-the-sand",
    rewardIds: ["boundary-flame"],
    unlockRequirements: [
      { type: "completedRitual", ritualId: "line-in-the-sand" },
    ],
  },
  {
    id: "remove-one-mask",
    title: "Remove One Mask",
    description: "Name one role you perform and practice one truthful action.",
    type: "room",
    roomId: "hall-of-masks",
    ritualId: "mask-removal",
    rewardIds: ["mask-shard"],
    unlockRequirements: [{ type: "completedRoom", roomId: "archetype-chamber" }],
  },
  {
    id: "recode-worthiness",
    title: "Recode Worthiness",
    description: "Replace a scarcity condition with a grounded worth statement.",
    type: "room",
    roomId: "scarcity-vault",
    ritualId: "worthiness-recode",
    rewardIds: ["scarcity-release"],
    unlockRequirements: [{ type: "trialDayMinimum", day: 7 }],
  },
  {
    id: "map-one-bond",
    title: "Map One Bond",
    description: "Map the needs, fears, and requests inside one relationship.",
    type: "room",
    roomId: "relationship-atrium",
    ritualId: "attachment-mapping",
    rewardIds: ["attachment-clarity"],
    unlockRequirements: [{ type: "completedRitual", ritualId: "line-in-the-sand" }],
  },
  {
    id: "integrate-the-work",
    title: "Integrate the Work",
    description: "Turn the strongest insight into a seven-day practice.",
    type: "daily",
    roomId: "integration-sanctuary",
    ritualId: "integration-ritual",
    rewardIds: ["integration-crown"],
    unlockRequirements: [
      { type: "completedRoom", roomId: "future-self-chamber" },
    ],
  },
];
