import type { Reward } from "@/domain/types";

export const rewards: readonly Reward[] = [
  {
    id: "arrival-spark",
    title: "Arrival Spark",
    description: "The first mark of choosing the journey.",
    statIncreases: { presence: 1, clarity: 1 },
    ascensionPoints: 5,
    unlockRoomIds: ["hall-of-echoes"],
  },
  {
    id: "pattern-sight",
    title: "Pattern Sight",
    description: "A clearer view of repeating inner loops.",
    statIncreases: { clarity: 2, emotionalRegulation: 1 },
    ascensionPoints: 8,
    unlockRoomIds: ["childhood-room"],
  },
  {
    id: "origin-compassion",
    title: "Origin Compassion",
    description: "A softer relationship with the first wound.",
    statIncreases: { compassion: 2, selfWorth: 1 },
    ascensionPoints: 8,
    unlockRoomIds: ["ancestral-chamber"],
  },
  {
    id: "shadow-courage",
    title: "Shadow Courage",
    description: "The strength to face what was avoided.",
    statIncreases: { courage: 2, presence: 1 },
    ascensionPoints: 10,
    unlockRoomIds: ["shadow-mirror-hall"],
  },
  {
    id: "archetype-sigil",
    title: "Archetype Sigil",
    description: "A symbol of the chosen inner path.",
    statIncreases: { intuition: 1, discipline: 1 },
    ascensionPoints: 10,
    sigilIds: ["archetype-sigil"],
    unlockRoomIds: ["archetype-chamber"],
  },
  {
    id: "thread-cutter",
    title: "Thread Cutter",
    description: "A clean break from an inherited emotional pattern.",
    statIncreases: { courage: 1, boundaries: 2 },
    ascensionPoints: 12,
    sigilIds: ["thread-cutter"],
    unlockRoomIds: ["hall-of-masks"],
  },
  {
    id: "library-key",
    title: "Library Key",
    description: "Access to the wider Akashic Library.",
    statIncreases: { clarity: 1, presence: 1 },
    ascensionPoints: 15,
    titleIds: ["library-initiate"],
    unlockRoomIds: [
      "chamber-of-boundaries",
      "scarcity-vault",
      "relationship-atrium",
    ],
  },
  {
    id: "boundary-flame",
    title: "Boundary Flame",
    description: "A steady inner no that protects the true yes.",
    statIncreases: { boundaries: 3, selfWorth: 1 },
    ascensionPoints: 10,
    unlockQuestIds: ["hold-a-clean-boundary"],
  },
  {
    id: "mask-shard",
    title: "Mask Shard",
    description: "A fragment of false performance returned to truth.",
    statIncreases: { selfWorth: 2, courage: 1 },
    ascensionPoints: 10,
    sigilIds: ["unmasked"],
  },
  {
    id: "scarcity-release",
    title: "Scarcity Release",
    description: "A shift from contraction into enoughness.",
    statIncreases: { selfWorth: 2, emotionalRegulation: 1 },
    ascensionPoints: 10,
  },
  {
    id: "attachment-clarity",
    title: "Attachment Clarity",
    description: "A map of bonds, bids, fears, and needs.",
    statIncreases: { clarity: 1, emotionalRegulation: 2 },
    ascensionPoints: 10,
  },
  {
    id: "future-vow",
    title: "Future Vow",
    description: "A commitment spoken from the self becoming real.",
    statIncreases: { discipline: 2, intuition: 1 },
    ascensionPoints: 12,
    unlockRoomIds: ["future-self-chamber"],
  },
  {
    id: "creative-spark",
    title: "Creative Spark",
    description: "A returned current of expressive life force.",
    statIncreases: { creativity: 3, presence: 1 },
    ascensionPoints: 8,
  },
  {
    id: "integration-crown",
    title: "Integration Crown",
    description: "A title earned by bringing the fragments into practice.",
    statIncreases: { clarity: 1, courage: 1, compassion: 1, discipline: 1 },
    ascensionPoints: 20,
    titleIds: ["integrated-initiate"],
    unlockRoomIds: ["integration-sanctuary"],
  },
  {
    id: "inner-child-gem",
    title: "Inner Child Gem",
    description: "A small light restored to the younger self.",
    statIncreases: { compassion: 2, emotionalRegulation: 1 },
    ascensionPoints: 8,
    sigilIds: ["inner-child-gem"],
  },
  {
    id: "transmutation-ash",
    title: "Transmutation Ash",
    description: "Proof that old material can become new power.",
    statIncreases: { courage: 1, creativity: 1, clarity: 1 },
    ascensionPoints: 12,
    sigilIds: ["transmutation-ash"],
  },
];
