import type { Ritual } from "@/domain/types";

export const rituals: readonly Ritual[] = [
  {
    id: "breath-of-arrival",
    title: "Breath of Arrival",
    description: "A grounding ritual for crossing the threshold.",
    roomId: "threshold-chamber",
    script: [
      "Place one hand on your chest and one hand on your stomach.",
      "Take seven slow breaths and name what is true right now.",
      "Write one sentence that begins with: I am willing to arrive.",
    ],
    journalPrompt: "What are you bringing to the threshold today?",
    rewardIds: ["arrival-spark"],
  },
  {
    id: "pattern-naming",
    title: "Pattern Naming",
    description: "A reflection ritual for seeing recurring emotional loops.",
    roomId: "hall-of-echoes",
    script: [
      "Choose one repeating situation from the last month.",
      "Name the trigger, the body response, and the familiar action.",
      "Write the hidden belief underneath the pattern.",
    ],
    journalPrompt: "What pattern is asking to be seen without judgment?",
    rewardIds: ["pattern-sight"],
  },
  {
    id: "first-memory",
    title: "First Memory",
    description: "A gentle return to the origin of a current emotional theme.",
    roomId: "childhood-room",
    script: [
      "Recall an early memory connected to the feeling you are working with.",
      "Describe the scene as if watching it from a compassionate distance.",
      "Offer the younger self one sentence they needed to hear.",
    ],
    journalPrompt: "What did the younger self decide in that moment?",
    rewardIds: ["origin-compassion"],
  },
  {
    id: "shadow-dialogue",
    title: "Shadow Dialogue",
    description: "A structured conversation with a disowned part.",
    roomId: "shadow-mirror-hall",
    script: [
      "Name the part of you that you usually reject.",
      "Ask what it protects, fears, and needs.",
      "Write a new agreement with that part.",
    ],
    journalPrompt: "What does the shadow want you to understand?",
    rewardIds: ["shadow-courage"],
  },
  {
    id: "archetype-activation",
    title: "Archetype Activation",
    description: "A ritual for choosing the archetype as a practice.",
    roomId: "archetype-chamber",
    script: [
      "Name your archetype and the gift it carries.",
      "Identify one behavior that would express that gift today.",
      "Write a vow in the voice of the archetype.",
    ],
    journalPrompt: "How will your archetype act through you today?",
    rewardIds: ["archetype-sigil"],
  },
  {
    id: "cutting-the-thread",
    title: "Cutting the Thread",
    description: "A symbolic release of an inherited pattern.",
    roomId: "ancestral-chamber",
    script: [
      "Name one pattern that did not begin with you.",
      "Thank it for the survival it once represented.",
      "Write the sentence: This can end with me.",
    ],
    journalPrompt: "What inherited thread are you ready to stop carrying?",
    rewardIds: ["thread-cutter"],
  },
  {
    id: "line-in-the-sand",
    title: "Line in the Sand",
    description: "A ritual for defining and honoring one boundary.",
    roomId: "chamber-of-boundaries",
    script: [
      "Name one place where your yes has become resentment.",
      "Write the clean no or clear request that protects your energy.",
      "Choose one action that proves the boundary is real.",
    ],
    journalPrompt: "What boundary would protect your becoming?",
    rewardIds: ["boundary-flame"],
  },
  {
    id: "lineage-mapping",
    title: "Lineage Mapping",
    description: "A map of inherited beliefs, loyalties, and strengths.",
    roomId: "ancestral-chamber",
    script: [
      "Write three messages your family system taught about safety.",
      "Circle the one you still obey automatically.",
      "Name one strength you want to keep from the lineage.",
    ],
    journalPrompt: "What did your lineage teach you to fear or value?",
    rewardIds: ["origin-compassion"],
  },
  {
    id: "mask-removal",
    title: "Mask Removal",
    description: "A ritual for separating truth from performance.",
    roomId: "hall-of-masks",
    script: [
      "Name one role you perform to earn safety or approval.",
      "Write what the role costs you.",
      "Describe one honest action that does not need the mask.",
    ],
    journalPrompt: "Which mask are you ready to loosen?",
    rewardIds: ["mask-shard"],
  },
  {
    id: "attachment-mapping",
    title: "Attachment Mapping",
    description: "A map of needs, fears, and bids inside relationship.",
    roomId: "relationship-atrium",
    script: [
      "Choose one important relationship.",
      "Name what you seek, fear, and withhold in that bond.",
      "Write one honest request that does not abandon you.",
    ],
    journalPrompt: "What pattern appears when closeness feels uncertain?",
    rewardIds: ["attachment-clarity"],
  },
  {
    id: "worthiness-recode",
    title: "Worthiness Recode",
    description: "A ritual for loosening scarcity from self-worth.",
    roomId: "scarcity-vault",
    script: [
      "Name the condition you place on being worthy.",
      "Write the earliest source of that condition if you know it.",
      "Replace it with a grounded statement of enoughness.",
    ],
    journalPrompt: "What would change if worth was not something to earn?",
    rewardIds: ["scarcity-release"],
  },
  {
    id: "spark-ritual",
    title: "Spark Ritual",
    description: "A small creative act that opens the future self path.",
    roomId: "future-self-chamber",
    script: [
      "Choose one tiny expression: words, movement, image, sound, or action.",
      "Create for five uninterrupted minutes.",
      "Name what the future self is trying to practice through you.",
    ],
    journalPrompt: "What spark wants to become a practice?",
    rewardIds: ["creative-spark", "future-vow"],
  },
  {
    id: "integration-ritual",
    title: "Integration Ritual",
    description: "A ritual for turning insight into a repeatable practice.",
    roomId: "integration-sanctuary",
    script: [
      "Review the three strongest insights from this journey.",
      "Choose one behavior that would make each insight visible.",
      "Write a seven-day integration commitment.",
    ],
    journalPrompt: "What must become practice now?",
    rewardIds: ["integration-crown"],
  },
  {
    id: "fire-of-transmutation",
    title: "Fire of Transmutation",
    description: "A ritual for converting charged emotion into clear action.",
    roomId: "shadow-mirror-hall",
    script: [
      "Name the emotion with the most heat.",
      "Write what it is trying to protect.",
      "Choose one clean action that uses the energy without harm.",
    ],
    journalPrompt: "What power is hidden inside this emotion?",
    rewardIds: ["transmutation-ash"],
  },
  {
    id: "inner-child-embrace",
    title: "Inner Child Embrace",
    description: "A repair ritual for meeting the younger self with care.",
    roomId: "childhood-room",
    script: [
      "Picture the younger self at the age that appears first.",
      "Ask what they needed and did not receive.",
      "Write a protective promise from the adult self.",
    ],
    journalPrompt: "What does the younger self need from you now?",
    rewardIds: ["inner-child-gem"],
  },
];
