import type { Ritual } from "@/domain/types";

export const rituals: readonly Ritual[] = [
  {
    id: "breath-of-arrival",
    title: "Breath of Arrival",
    description: "A grounding ritual for arriving safely at the threshold of the inner world.",
    roomId: "threshold-chamber",
    script: [
      "Find a quiet position and let your body be supported.",
      "Place one hand on your chest or stomach.",
      "Take one slow breath in.",
      "Let the breath leave without forcing it.",
      "Notice one place where your body touches the ground or seat.",
      "Look around and name one thing that tells you this moment is safe enough.",
      "Let your shoulders soften by a small amount.",
      "Say quietly: I am here.",
      "Take one final breath and let the ritual close.",
    ],
    journalPrompt: "What do you notice in your body right now, without trying to change it?",
    rewardIds: ["arrival-spark"],
  },
  {
    id: "pattern-naming",
    title: "Pattern Naming",
    description: "A mirror ritual for noticing one repeating pattern without judgment.",
    roomId: "hall-of-echoes",
    script: [
      "Sit as if you are facing a still mirror.",
      "Choose one situation that has repeated in your life.",
      "Name only the shape of it, not the reason for it.",
      "Notice what usually happens before the pattern begins.",
      "Notice what you tend to feel in your body.",
      "Notice what action you usually take next.",
      "Let the pattern have a simple name.",
      "Say quietly: I can see this now.",
      "Take one breath and let the mirror fade.",
    ],
    journalPrompt: "What pattern do you notice repeating in your life?",
    rewardIds: ["pattern-sight"],
  },
  {
    id: "first-memory",
    title: "First Memory",
    description: "A gentle memory ritual for noticing where a pattern may have first taken root.",
    roomId: "childhood-room",
    script: [
      "Begin with the pattern you named before.",
      "Let your attention move gently toward an earlier time.",
      "Do not search hard; allow only what comes easily.",
      "If a memory appears, notice the scene from a safe distance.",
      "Notice the age or feeling that stands out.",
      "Notice what the younger self may have needed in that moment.",
      "You do not need to solve or explain anything.",
      "Offer one simple sentence of kindness.",
      "Take one breath and return to the room you are in.",
    ],
    journalPrompt: "When did you first feel this pattern?",
    rewardIds: ["origin-compassion"],
  },
  {
    id: "shadow-dialogue",
    title: "Shadow Dialogue",
    description: "A witnessing ritual for meeting the part of you that has been kept out of view.",
    roomId: "shadow-mirror-hall",
    script: [
      "Sit somewhere quiet and take one steady breath.",
      "Imagine a dim room with a mirror in front of you.",
      "Let one avoided part of you appear only as much as feels safe.",
      "Name this part with simple words.",
      "Notice what this part seems to protect.",
      "Notice what this part may fear.",
      "Listen without arguing with it.",
      "Say quietly: I can witness you without becoming you.",
      "Take one breath and let the mirror darken.",
      "Return your attention to the room around you.",
    ],
    journalPrompt: "What does this part of you want or fear?",
    rewardIds: ["shadow-courage"],
  },
  {
    id: "archetype-activation",
    title: "Archetype Activation",
    description: "An identity ritual for stepping toward the direction your archetype represents.",
    roomId: "archetype-chamber",
    script: [
      "Stand or sit with your spine gently lifted.",
      "Name your archetype in a clear voice or quiet thought.",
      "Picture a doorway marked with that archetype's symbol.",
      "Notice the quality this archetype carries.",
      "Let that quality become one simple posture in your body.",
      "Ask what direction this archetype points you toward today.",
      "Choose one small action that matches that direction.",
      "Say quietly: I can practice this one step.",
      "Take one breath and let the symbol fade.",
    ],
    journalPrompt: "What would this version of you do differently?",
    rewardIds: ["archetype-sigil"],
  },
  {
    id: "cutting-the-thread",
    title: "Cutting the Thread",
    description: "A completion ritual for releasing one pattern and crossing into the wider Library.",
    roomId: "ancestral-chamber",
    script: [
      "Begin with one slow breath and feel the ground beneath you.",
      "Name the pattern you are ready to release for now.",
      "Imagine it as a thread held gently between your hands.",
      "Notice where the thread has pulled your attention.",
      "Thank the thread for what it tried to protect.",
      "Let your hands open in your own time.",
      "Imagine the thread loosening and falling away.",
      "Say quietly: I can step forward without carrying this the same way.",
      "Take one final breath for completion.",
      "Picture the Library doors opening ahead of you.",
    ],
    journalPrompt: "What are you ready to release?",
    rewardIds: ["thread-cutter"],
  },
  {
    id: "line-in-the-sand",
    title: "Line in the Sand",
    description: "A ritual for defining and honoring one boundary.",
    roomId: "chamber-of-boundaries",
    script: [
      "Name one place where your yes has become resentment.",
      "Write the clean no or clear request that protects your energy.",
      "Choose one action that proves the boundary is real.",
    ],
    journalPrompt: "What boundary would protect your becoming?",
    rewardIds: ["boundary-flame"],
  },
  {
    id: "lineage-mapping",
    title: "Lineage Mapping",
    description: "A map of inherited beliefs, loyalties, and strengths.",
    roomId: "ancestral-chamber",
    script: [
      "Write three messages your family system taught about safety.",
      "Circle the one you still obey automatically.",
      "Name one strength you want to keep from the lineage.",
    ],
    journalPrompt: "What did your lineage teach you to fear or value?",
    rewardIds: ["origin-compassion"],
  },
  {
    id: "mask-removal",
    title: "Mask Removal",
    description: "A ritual for separating truth from performance.",
    roomId: "hall-of-masks",
    script: [
      "Name one role you perform to earn safety or approval.",
      "Write what the role costs you.",
      "Describe one honest action that does not need the mask.",
    ],
    journalPrompt: "Which mask are you ready to loosen?",
    rewardIds: ["mask-shard"],
  },
  {
    id: "attachment-mapping",
    title: "Attachment Mapping",
    description: "A map of needs, fears, and bids inside relationship.",
    roomId: "relationship-atrium",
    script: [
      "Choose one important relationship.",
      "Name what you seek, fear, and withhold in that bond.",
      "Write one honest request that does not abandon you.",
    ],
    journalPrompt: "What pattern appears when closeness feels uncertain?",
    rewardIds: ["attachment-clarity"],
  },
  {
    id: "worthiness-recode",
    title: "Worthiness Recode",
    description: "A ritual for loosening scarcity from self-worth.",
    roomId: "scarcity-vault",
    script: [
      "Name the condition you place on being worthy.",
      "Write the earliest source of that condition if you know it.",
      "Replace it with a grounded statement of enoughness.",
    ],
    journalPrompt: "What would change if worth was not something to earn?",
    rewardIds: ["scarcity-release"],
  },
  {
    id: "spark-ritual",
    title: "Spark Ritual",
    description: "A small creative act that opens the future self path.",
    roomId: "future-self-chamber",
    script: [
      "Choose one tiny expression: words, movement, image, sound, or action.",
      "Create for five uninterrupted minutes.",
      "Name what the future self is trying to practice through you.",
    ],
    journalPrompt: "What spark wants to become a practice?",
    rewardIds: ["creative-spark", "future-vow"],
  },
  {
    id: "integration-ritual",
    title: "Integration Ritual",
    description: "A ritual for turning insight into a repeatable practice.",
    roomId: "integration-sanctuary",
    script: [
      "Review the three strongest insights from this journey.",
      "Choose one behavior that would make each insight visible.",
      "Write a seven-day integration commitment.",
    ],
    journalPrompt: "What must become practice now?",
    rewardIds: ["integration-crown"],
  },
  {
    id: "fire-of-transmutation",
    title: "Fire of Transmutation",
    description: "A ritual for converting charged emotion into clear action.",
    roomId: "shadow-mirror-hall",
    script: [
      "Name the emotion with the most heat.",
      "Write what it is trying to protect.",
      "Choose one clean action that uses the energy without harm.",
    ],
    journalPrompt: "What power is hidden inside this emotion?",
    rewardIds: ["transmutation-ash"],
  },
  {
    id: "inner-child-embrace",
    title: "Inner Child Embrace",
    description: "A repair ritual for meeting the younger self with care.",
    roomId: "childhood-room",
    script: [
      "Picture the younger self at the age that appears first.",
      "Ask what they needed and did not receive.",
      "Write a protective promise from the adult self.",
    ],
    journalPrompt: "What does the younger self need from you now?",
    rewardIds: ["inner-child-gem"],
  },
];
