import type { Room } from "@/domain/types";

export const rooms: readonly Room[] = [
  {
    id: "threshold-chamber",
    name: "Threshold Chamber",
    description: "The first room of arrival, breath, and consent to begin.",
    ritualIds: ["breath-of-arrival"],
    bossIds: [],
    rewardIds: ["arrival-spark"],
    unlockRequirements: [],
  },
  {
    id: "hall-of-echoes",
    name: "Hall of Echoes",
    description: "A corridor where repeating patterns become visible.",
    ritualIds: ["pattern-naming"],
    bossIds: ["critic"],
    rewardIds: ["pattern-sight"],
    unlockRequirements: [{ type: "trialDayMinimum", day: 2 }],
  },
  {
    id: "childhood-room",
    name: "Childhood Room",
    description: "A memory chamber for meeting the earliest emotional imprint.",
    ritualIds: ["first-memory", "inner-child-embrace"],
    bossIds: ["shadow-child", "abandoner"],
    rewardIds: ["origin-compassion", "inner-child-gem"],
    unlockRequirements: [{ type: "completedRitual", ritualId: "pattern-naming" }],
  },
  {
    id: "ancestral-chamber",
    name: "Ancestral Chamber",
    description: "A room of inherited threads, family stories, and release.",
    ritualIds: ["lineage-mapping", "cutting-the-thread"],
    bossIds: ["ancestral-thread"],
    rewardIds: ["thread-cutter"],
    unlockRequirements: [{ type: "trialDayMinimum", day: 4 }],
  },
  {
    id: "shadow-mirror-hall",
    name: "Shadow Mirror Hall",
    description: "A mirror-lined passage where avoided parts ask to be seen.",
    ritualIds: ["shadow-dialogue", "fire-of-transmutation"],
    bossIds: ["avoider", "saboteur"],
    rewardIds: ["shadow-courage", "transmutation-ash"],
    unlockRequirements: [{ type: "completedRitual", ritualId: "first-memory" }],
  },
  {
    id: "archetype-chamber",
    name: "Archetype Chamber",
    description: "A central chamber for activating the user's inner pattern.",
    ritualIds: ["archetype-activation"],
    bossIds: ["ghost"],
    rewardIds: ["archetype-sigil"],
    unlockRequirements: [{ type: "trialDayMinimum", day: 5 }],
  },
  {
    id: "hall-of-masks",
    name: "Hall of Masks",
    description: "A gallery of roles, performances, and protective identities.",
    ritualIds: ["mask-removal"],
    bossIds: ["performer"],
    rewardIds: ["mask-shard"],
    unlockRequirements: [{ type: "defeatedBoss", bossId: "ghost" }],
  },
  {
    id: "chamber-of-boundaries",
    name: "Chamber of Boundaries",
    description: "A stone room for drawing clean lines around the self.",
    ritualIds: ["line-in-the-sand"],
    bossIds: ["martyr"],
    rewardIds: ["boundary-flame"],
    unlockRequirements: [{ type: "completedRitual", ritualId: "cutting-the-thread" }],
  },
  {
    id: "scarcity-vault",
    name: "Scarcity Vault",
    description: "A locked vault of fear, lack, worth, and enoughness.",
    ritualIds: ["worthiness-recode"],
    bossIds: ["scarcity-beast"],
    rewardIds: ["scarcity-release"],
    unlockRequirements: [{ type: "trialDayMinimum", day: 7 }],
  },
  {
    id: "relationship-atrium",
    name: "Relationship Atrium",
    description: "An open chamber for mapping attachment and relational truth.",
    ritualIds: ["attachment-mapping"],
    bossIds: ["clinger"],
    rewardIds: ["attachment-clarity"],
    unlockRequirements: [{ type: "completedRitual", ritualId: "line-in-the-sand" }],
  },
  {
    id: "future-self-chamber",
    name: "Future Self Chamber",
    description: "A luminous room where the next self offers direction.",
    ritualIds: ["spark-ritual"],
    bossIds: ["chaos-weaver"],
    rewardIds: ["future-vow", "creative-spark"],
    unlockRequirements: [{ type: "ascensionPointsMinimum", minimum: 50 }],
  },
  {
    id: "integration-sanctuary",
    name: "Integration Sanctuary",
    description: "A quiet sanctuary where earned insight becomes daily practice.",
    ritualIds: ["integration-ritual"],
    bossIds: [],
    rewardIds: ["integration-crown"],
    unlockRequirements: [{ type: "completedRoom", roomId: "future-self-chamber" }],
  },
];
